apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: ejemplo

resources:
  - 15-pod-secret.yaml

secretGenerator:
  - name: db-credentials
    literals:
      - username=admin # it should be passed through a different file!
      - password=secr3tpassw0rd!!! # it should be passed through a different file!

images:
  - name: nginx
    newTag: latest
